# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20210523_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
