# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20210523_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='nick_name',
            field=models.CharField(default='no nick nama', max_length=50),
            preserve_default=False,
        ),
    ]
