# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2021-05-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_translator_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
